export const role=[
  "Doctor",
  "Receptionist",
  "Pharmacist"
]


export const purposeOfVisit=[
  'Hair treatment', 
  'Face treatment',
  'Neck treatment',
  'Chest treatment' ,
  'Breast treatment', 
  'Fat reduction', 
  'Body treatments',
  'Hair reduction ',
  'Leg and hand treatments', 
  'Skin treatments',
  'Skin brightening and lightening'
]

export const consumerItems = [
  'Gloves',
  'needles',
    ];

const patientComplaints = [
"Dislike of nasal shape or size",
"Bumps or humps on the nasal bridge",
"Wide or flared nostrils",
"Crooked or asymmetrical nose",
"Breathing difficulties due to structural issues",
"Droopy upper eyelids",
"Excess skin on the eyelids",
"Bags or puffiness under the eyes",
"Dark circles around the eyes",
"Sagging facial skin",
"Deep wrinkles or facial folds",
"Jowls along the jawline",
"Loose skin or double chin",
"Asymmetrical or weak chin",
"Wrinkles on the forehead and between the eyebrows",
"Low or drooping eyebrows",
"Protruding or overly large ears",
"Ear asymmetry",
"Small or underdeveloped breasts",
"Breasts that are too large and cause discomfort",
"Uneven or asymmetrical breasts",
"Sagging or drooping breasts",
"Loss of breast volume or shape after pregnancy or weight loss",
"Enlarged male breasts",
"Excess abdominal fat",
"Loose or sagging abdominal skin",
"Stretch marks on the abdomen",
"Separated or weak abdominal muscles",
"Excess fat on the thighs or arms",
"Loose or sagging skin on the upper arms or thighs",
"Localized fat deposits resistant to diet and exercise",
"Cellulite on thighs, buttocks, or abdomen",
"Fine lines and wrinkles over face",
"Age spots or sun damage over face and neck",
"Uneven skin tone or texture over face",
"Acne scars or other facial scarring",
"Hyperpigmentation or melasma",
"Hair loss or thinning",
"Unwanted hair in specific areas",
"Thin or uneven lips",
"Loss of volume in cheeks",
"Unwanted tattoos",
"Excessive sweating"
];

const findingsList = [
" Deviated septum",
"Nasal asymmetry",
" Nasal humps",
" Nasal tip deformities",
"Drooping eyelids",
"Ptosis",
"Excess eyelid skin",
"Under-eye bags",
" Sagging facial skin",
" Deep wrinkles or creases",
" Loss of muscle tone in the face and neck",
"Breast asymmetry",
"Macromastia (overly large breasts)",
"Micromastia (underdeveloped breasts)",
"Breast ptosis (sagging breasts)",
" Gynecomastia (enlarged male breasts)",
"Localized fat deposits resistant to diet and exercise",
" Lipodystrophy (abnormal distribution of fat)",
" Excess abdominal skin and fat",
"Weakened or separated abdominal muscles",
"Protruding ears",
" Ear deformities",
"Recessed chin",
"Facial imbalance",
"Flat or sunken cheeks",
"Loss of volume in the mid-face",
"Sagging eyebrows",
"Forehead wrinkles",
"Frown lines",
"Facial wrinkles",
"Loss of facial volume",
"Crow's feet",
"Lip enhancement",
"Sun-damaged skin",
"Acne scars",
"Fine lines and wrinkles",
"Hyperpigmentation",
"Androgenetic alopecia (male-pattern baldness)",
"Thinning hair",
"Excess skin after massive weight loss",
"Loose or sagging skin in various body areas",
"Hypertrophic scars",
"Keloid scars",
"Contracture scars"
];

const diagnosisList = [
"Nasal deformity",
"Deviated septum",
"Nasal asymmetry",
"Gynecomastia",
"Excess skin after massive weight loss",
"Lipodystrophy",
"Gender dysphoria",
"Desire for feminized facial features",
"Chest dysphoria",
"Hypertrophic scars",
"Keloid scars",
"Contracture scars",
"Post-mastectomy reconstruction",
"Congenital breast deformities",
"Volume loss",
"Static wrinkles",
"Facial asymmetry",
"Dynamic wrinkles",
"Hyperhidrosis",
"Age spots",
"Skin laxity",
"Scars",
"Dyschromia (skin discoloration)",
"Fine lines",
"Sun-damaged skin",
"Breast ptosis (sagging breasts)",
"Loss of breast volume",
"Acne scars",
"Facial scars",
"Sun damage",
"Macromastia (overly large breasts)",
"Breast ptosis",
"Back pain due to breast size",
"Hypomastia (underdeveloped breasts)",
"Breast asymmetry",
"Diastasis recti (separation of abdominal muscles)",
"Excess abdominal skin",
"Abdominal wall laxity",
"Lipodystrophy (uneven fat distribution)",
"Localized adiposity",
"Microgenia (small chin)",
"Chin deformity",
"Prominent ears",
"Ear deformities",
"Dermatochalasis (excess eyelid skin)",
"Ptosis (drooping eyelid)",
"Periorbital puffiness",
"Facial wrinkles",
"Sagging skin",
"Loss of muscle tone"
];

const planList = [
"Rhinoplasty",
"Blepharoplasty (Eyelid Surgery)",
"Rhytidectomy (Facelift)",
"Otoplasty (Ear Surgery)",
"Chin Augmentation",
"Liposuction",
"Abdominoplasty (Tummy Tuck)",
"Breast Augmentation",
"Breast Reduction",
"Breast Lift (Mastopexy)",
"Dermabrasion",
"Chemical Peel",
"Laser Resurfacing",
"Botox Injections",
"Dermal Fillers",
"Breast Reconstruction",
"Scar Revision Surgery",
"Female to Male Chest Surgery",
"Male to Female Chest Surgery",
"Facial Feminization Surgery",
"Gynecomastia Surgery",
"Body Contouring"
];


const prescription = [
"SELF ADJUSTING SUNSCREEN",
"SUNSCREEN SLICONE GEL",
"MULTI VITAMIN MOISTURIZING LOTION",
"HQ 2 MULTI ACTION SKIN LIGHTENING GEL",
"VITAMIN C SERUM",
"SKIN LIGHTENING GEL",
"STRETCHMARKS CREAM",
"FOOT GUARD GEL",
"COFFEE SCRUB",
"THIONE BAR SOAP",
"VIGHT AGE DERMA",
"DANDRUFF CONTROL SHAMPOO",
"HAIRFALL CONTROL SHAMPOO",
"HAIR GROWTH SERUM",
"HAIR MASK",
"GLUZHO WHITE SOAP",
"ANACSO SOAP",
"GLUZHO-WHITE G-VC SERUM",
"GLINT & GLOW",
"MELALIMIN LIP LIGHTENER",
"NIGRITOP CREAM",
"HAIR BUILDING FIBERS BLACK",
"GROVIVA HERBAL HAIR OIL",
"GLYCOLITE MAX FACE WASH",
"PRIOGLO+ SOAP",
"PRIOGLO EA SKIN LIGHTENING BODY LOTION",
"PRIOGLO SKIN LIGHTENING COMPLEX CREAM",
"PREMIUM REVITOSIN FACE CREAM",
"SUNRIV SPF 50 PA+++ GEL",
"SUNRIV ULTRA SPF 50 PA+++ MATTE FINISH SUNSCREEN",
"GLURIV-C VITAMIN-C SERUM",
"RIVIMED GEL",
"RIVOSAP MOISTURIZING CREAM",
"ACRIV ACNE FACE WASH",
"ACRIV ULTRA FACE WASH",
"ACRIV GEL",
"ACRIV SERUM ULTRA",
"RIVIWHITE CREAM",
"RIVIWHITE CREAM-ULTRA",
"CETORIVGOLD ANTI-DANDRUFF SHAMPOO",
"ONRIV HAIR SERUM",
"CETORIVGOLD SOAP",
"ONRIV HAIR REGROWTH OIL",
"F-TRICHO NOURISH EVA",
"F-TRICHOSILK HAIR SERUM",
"F-EMUGROW-MC-R PURE EMU OIL",
"F-TRICHO NOURISH GEL"
];

const test = [
// Hematology
"CBC (Hb, TC, DC, PLT, RBC, PCV)",
"Hb",
"Total RBC count",
"ESR",
"Total WBC Count / Differential Count",
"Platelet count",
"Absolute Neutrophil count",
"Absolute Eosinophil count",
"Absolute Lymphocyte count",
"Reticulocyte count",
"Coombs Test - Direct / Indirect",
"Peripheral Smear",
"QBC MP",
"QBC for MP",
"Smear for MP",
"Blood Group / Rh Type",
"IR Type",
// Biochemistry
"GTT",
"RBS",
"FBS",
"PPBS",
"Blood Sugar",
"Hb A1C",
"Urea",
"Creatinine",
"Uric acid",
"Calcium",
"Phosphorous",
"Total Proteins",
"Albumin",
"Globulin",
"A/G Ratio",
"SGOT",
"SGPT",
"ALP",
"Gamma GT",
// Coagulation Profile
"PT",
"APTT",
"BT / CT",
"Fibrinogen",
"D-Dimer",
// Serum Electrolytes
"Sodium",
"Potassium",
"Chloride",
"Bicarbonate",
// Lipid Profile
"Total Cholesterol",
"Triglycerides",
"HDL - Cholesterol",
"LDL - Cholesterol",
"VLDL",
"Risk factor Ratio",
// Liver Function Test
"Bilirubin Total Direct",
"Total Proteins",
"Albumin",
"Globulin",
"A/G Ratio",
"SGOT",
"SGPT",
"ALP",
"Gamma GT",
// Pancreatic Function Test
"Amylase",
"Lipase",
// Cardiac Markers
"CPK",
"CPK - MB",
"LDH",
"Trop - T (Qualitative)",
"Blood Gas Analysis (ABG)",
// Clinical Pathology
"Complete Urine Analysis",
"Urine Routine (Sug, Alb, Dep)",
"Urine Sugar",
"Urine Albumin",
"Urine Acetone",
"Bile Salts & Bile Pigments",
"Urobilinogen",
"Bence Jones Protein",
"Urine for Gravidex",
// 24 Hours Urine / Spot Urine
"Protein",
"Creatinine",
"Protein Creatinine Ratio",
// Motion Analysis
"Routine",
"Motion for occult blood",
"Reducing Substances",
"Hanging drop examination",
// Tumour Markers
"CEA",
"CA-125",
"PSA",
"Alfa Feto Protein",
// Fluid Analysis
"CSF",
"Pleural",
"Ascitic",
"Synovial",
"Others",
// Serology / Virology
"ASO",
"CRP",
"RA Factor",
"Chikungunya IgM",
"VDRL",
"Widal Slide test / Tube agglutination",
"Hbs Ag",
"HIV I & II",
"Anti HCV",
"Dengu IgG / IgM / NS1 Ag",
"Leptospira IgG / IgM",
"Malaria PF / PV Ag",
// Microbiology
"Culture & Sensitivity",
"Blood",
"Urine",
"Sputum",
"Throat Swab",
"Pus & Wound",
"CSF",
"Vaginal Swab",
"Semen",
"Stool",
"Body Fluids",
"Fungal Culture",
"Smear For Fungus",
"Gram Stain",
"Smear For AFB",
// Endocrinology
"Total T3",
"Total T4",
"TSH",
"Free T3",
"Free T4",
"LH",
"FSH",
"Prolactin",
"Beta HCG",
"Estradiol",
"Progesterone",
"Testosterone",
"Insulin",
"Cortisol",
"Vitamin D3",
"Vitamin B12"
];

export {
patientComplaints,
findingsList,
diagnosisList,
planList,
prescription,
test 
};